version: '3.8'

services:
  hidroqu-app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "9000:9000"
    volumes:
      - hidroqu-data:/var/www/html
    networks:
      - hidroqu-project

networks:
  hidroqu-project:

volumes:
  hidroqu-data:
