version: "3"

services:
  hidroqu-caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - hidroqu-data:/var/www/html
    depends_on:
      - hidroqu-api
    networks:
      - hidroqu-project

  hidroqu-api:
    image: hidroqu/hidroqu-api:latest
    restart: unless-stopped
    networks:
      - hidroqu-project

networks:
  hidroqu-project:
